// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using CarStore.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace CarStore.Models
{
    public partial class CarStoreContext
    {
        private ICarStoreContextProcedures _procedures;

        public virtual ICarStoreContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new CarStoreContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public ICarStoreContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
        }
    }

    public partial class CarStoreContextProcedures : ICarStoreContextProcedures
    {
        private readonly CarStoreContext _context;

        public CarStoreContextProcedures(CarStoreContext context)
        {
            _context = context;
        }
    }
}
